# Generated by Django 4.2.28 on 2026-02-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_duration', models.PositiveIntegerField(default=30, help_text='Default meeting duration in minutes.')),
                ('buffer_before_minutes', models.PositiveIntegerField(default=0, help_text='Buffer time before a meeting in minutes.')),
                ('buffer_after_minutes', models.PositiveIntegerField(default=15, help_text='Buffer time after a meeting in minutes.')),
                ('weekend_off', models.BooleanField(default=True, help_text='If True, Saturday and Sunday are marked as off days.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'core_system_settings',
            },
        ),
    ]
