# Generated by Django 5.2.11 on 2026-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
