# Generated by Django 5.2.11 on 2026-02-22 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslot',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='is_booked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['date', 'is_booked'], name='availabilit_date_4eda03_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['admin', 'date'], name='availabilit_admin_i_abd812_idx'),
        ),
    ]
